name: hexagonal_puzzle
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  sprintf: ^6.0.0
  flutter_svg: ^1.1.5
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Lemon
      fonts:
        - asset: assets/fonts/Lemon-Regular.ttf
          style: normal
          weight: 400

  assets:
    # list of levels
    - assets/levels_description.json

    # localisation
    - assets/translations/

    # level images
    - assets/images/levels/large/
    - assets/images/levels/small/

    # other images
    - assets/images/

    # icons
    - assets/icons/
